# Generated by Django 2.0 on 2018-01-13 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zoop', '0003_auto_20180112_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_poster',
            field=models.ForeignKey(default=1, on_delete=models.SET('deleted_user'), related_name='author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
