# Generated by Django 2.0 on 2018-01-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0004_post_original_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReactions',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='zoop.Post')),
                ('react_one', models.IntegerField(default=0)),
                ('react_two', models.IntegerField(default=0)),
                ('react_three', models.IntegerField(default=0)),
                ('react_four', models.IntegerField(default=0)),
                ('react_five', models.IntegerField(default=0)),
                ('react_six', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
