# Generated by Django 2.0 on 2018-01-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0006_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='description',
            field=models.CharField(default=None, max_length=3000),
            preserve_default=False,
        ),
    ]
